name: Build distributable theme files

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create local changes
        run: |
          yarn install
          gulp
      - name: Commit and push local changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: Apply theme changes
